### ISSUE TITLE
Hiding API key

### ISSUE THREAD

**Issue by purplehaze2602** [tempo-riz/deepgram_speech_to_text#11]
Hey, is there any way to hide the API key on the frontend or is it necessary to use a backend service?

**Comment by zamirszn** [comment]
you can use dart define to compile your api key at build time

**Comment by zamirszn** [comment]
> Hey, is there any way to hide the API key on the frontend or is it necessary to use a backend service?

you can use dart define to compile your api key at build time

**Comment by tempo-riz** [comment]
You have multiple ways to pass env variables:

- using --dart-define="your api key" then Platform.fromEnvironnement()
- you can also use packages to make your life easier : https://pub.dev/packages/flutter_dotenv or https://pub.dev/packages/dotenv without flutter

**Comment by zamirszn** [comment]
@purplehaze2602 if youre hiding your key for security reasons I'll suggest you use dart-define , your key is still vulnerable if stored in a .env file as it can be extracted
