### ISSUE TITLE
Unhandled Exception: RangeError (code): Invalid value: Not in inclusive range 3000..4999: 1000

### ISSUE THREAD

**Issue by giapsoft** [tempo-riz/deepgram_speech_to_text#12]
please check when close the stream, below error appear

 #0      RangeError.checkValueInInterval (dart:core/errors.dart:313:7)
[        ] #1      checkCloseCode (package:web_socket/src/utils.dart:10:16)
[        ] #2      IOWebSocket.close (package:web_socket/src/io_web_socket.dart:108:5)
[        ] #3      new AdapterWebSocketChannel.<anonymous closure>.<anonymous closure> (package:web_socket_channel/adapter_web_socket_channel.dart:112:27)
[        ] #4      _RootZone.runGuarded (dart:async/zone.dart:1582:10)
[        ] #5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418:13)
[        ] #6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428:7)
[        ] #7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:317:7)
[        ] #8      _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:792:19)
[        ] #9      _StreamController._closeUnchecked (dart:async/stream_controller.dart:647:7)
[        ] #10     _StreamController.close (dart:async/stream_controller.dart:640:5)
[        ] #11     new GuaranteeChannel.<anonymous closure>.<anonymous closure> (package:stream_channel/src/guarantee_channel.dart:55:31)
[        ] #12     _RootZone.runGuarded (dart:async/zone.dart:1582:10)
[        ] #13     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418:13)
[        ] #14     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428:7)
[        ] #15     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:317:7)
[        ] #16     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:792:19)
[        ] #17     _StreamController._closeUnchecked (dart:async/stream_controller.dart:647:7)
[        ] #18     _StreamController.close (dart:async/stream_controller.dart:640:5)
[        ] #19     _StreamSinkWrapper.close (dart:async/stream_controller.dart:884:29)
[        ] #20     _GuaranteeSink.close (package:stream_channel/src/guarantee_channel.dart:188:38)
[        ] #21     DelegatingStreamSink.close (package:async/src/delegate/stream_sink.dart:47:27)
[        ] #22     _WebSocketSink.close (package:web_socket_channel/adapter_web_socket_channel.dart:147:18)
[        ] #23     DeepgramLiveTranscriber.close (package:deepgram_speech_to_text/src/deepgram.dart:77:27)
[        ] #24     DeepgramLiveTranscriber.start.<anonymous closure> (package:deepgram_speech_to_text/src/deepgram.dart:69:7)
[        ] #25     _RootZone.runGuarded (dart:async/zone.dart:1582:10)
[        ] #26     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418:13)
[        ] #27     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428:7)
[        ] #28     _DelayedDone.perform (dart:async/stream_impl.dart:560:14)
[        ] #29     _PendingEvents.handleNext (dart:async/stream_impl.dart:646:11)
[        ] #30     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617:7)
[        ] #31     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
[        ] #32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

**Comment by tempo-riz** [comment]
Hi @giapsoft are you using the latest version of the package ? If so can you provide a code sample for this ?

**Comment by tempo-riz** [comment]
should be fixed in 2.3.0, reopen if still happens
