### ISSUE TITLE
Failed to start listening: WebSocketChannelException: Instance of 'WebSocketException'

### ISSUE THREAD

**Issue by athvaith8282** [tempo-riz/deepgram_speech_to_text#19]
Hey, I am using the deegram_speech_to_text package for macos, 

I am using createlivetranscribe function, on starting it , I am getting the error 

"Failed to start listening: WebSocketChannelException: Instance of 'WebSocketException''

This the code:

Future<void> CreateTranscriber() async {
    if (!await _audioRecorder.hasPermission()) {
      throw Exception('Microphone permission not granted');
    }

    _transcriptionController = StreamController<String>.broadcast();

    final rawStream = await _audioRecorder.startStream(const RecordConfig(
      encoder: AudioEncoder.pcm16bits,
      sampleRate: 16000,
      numChannels: 1,
    ));

    _transcriber = _deepgram.createLiveTranscriber(
      rawStream,
    );

    _transcriber?.stream.listen(
      (result) {
        if (result.transcript?.isNotEmpty ?? false) {
          _transcriptionController?.add(result.transcript!);
        }
      },
      onError: (error) {
        _transcriptionController?.addError(error);
      },
    );
  }

  Future<void> startListening() async {
    await _transcriber?.start();
  }
  
  How to resolve this ?

**Comment by tempo-riz** [comment]
Hello, it could be because you are didn't specify your stream config, try to pass this in createLiveTranscriber's params or deepgram's constructor baseQuersParams : 

`final streamParams = {
  'detect_language': false, // not supported by streaming API
  'language': 'en',
  // must specify encoding and sample_rate according to the audio stream
  'encoding': 'linear16',
  'sample_rate': 16000,
};`

**Comment by tempo-riz** [comment]
I tested again on my side, everything works fine so you must do something wrong...
Did you try `deepgram.isApiKeyValid()` ?
If so maybe you can try to show more of your code so maybe I can help :)

**Comment by tempo-riz** [comment]
hey @athvaith8282 did you solve the issue ?

**Comment by Athvaith2803** [comment]
Hey @tempo-riz, Sorry for the late response, 

Yeah, There is a issue with api key permissions, I have created the right one, now its working, Thanks for the support !
And One more doubt, For live transcribe, is there a way to get a string of all the transcribed words (now i am just getting it in a bit by bit way) ?

**Comment by tempo-riz** [comment]
For streaming, I think you can play with parameters to specifiy the delay (how much time the servers wait before processing the data, e.g the end of your sentence) but that's still streaming, then you have to manage the result yourself
