### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by AndryHTC** [tempo-riz/deepgram_speech_to_text#2]

**Comment by tempo-riz** [comment]
I thought it would already be combatible with web (it should), I looked why it isn't and apparently dart:io isn't supported on web, so I will look for alternatives :)

**Comment by tempo-riz** [comment]
I just added WEB support.

**Comment by tempo-riz** [comment]
nevermind not yet but soon :)

**Comment by AndryHTC** [comment]
@tempo-riz do not worry. I've implemented realtime in Web successfully, but I still think this package is useful and I would prefer to use this instead.

To implement the authentication with WebSockets, Deepgram team added an alternative https://github.com/orgs/deepgram/discussions/175
