### ISSUE TITLE
Does it support 'Text-to-Speech Streaming' yet?

### ISSUE THREAD

**Issue by paulVu** [tempo-riz/deepgram_speech_to_text#20]
Thank you for building it, 
Does it support 'Text-to-Speech Streaming' yet?, I don't see the guide to setup for 'streaming'
https://developers.deepgram.com/docs/tts-websocket

**Comment by tempo-riz** [comment]
Hey @paulVu you are right it's not yet implemented, I missed it's release, I'll look into it :)

**Comment by tempo-riz** [comment]
@paulVu now it does in 3.0.0 :)
Check `deepgram.speak.live()` or `deepgram.speak.liveSpeaker()`

**Comment by paulVu** [comment]
Thank you so much, you are rock
