### ISSUE TITLE
non-platform thread

### ISSUE THREAD

**Issue by jonnyjohnson1** [tempo-riz/deepgram_speech_to_text#3]
When running this line:
`Stream<String> jsonStream = deepgram.transcribeFromLiveAudioStream(mic.stream);`

I get this error

```
The '[aaron.code.com/mic_stream](http://aaron.code.com/mic_stream)' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
```

This [SO](https://stackoverflow.com/questions/77720989/how-to-handle-platform-thread-without-plugin-in-flutter-from-native-ios) seems to point to a possible solution to use:
```
DispatchQueue.main.async {
  // Make your invokeMethod calls here.
}
```
But I can't find in the package where this would be applied.

I am running Flutter version at 3.16.9.

**Comment by tempo-riz** [comment]
hey !
Since this package is pure dart and doesnt rely on platform specific code I would say your error comes from the mic_stream package you are apparently using.
