### ISSUE TITLE
Deepgram Community Support of this project?

### ISSUE THREAD

**Issue by jpvajda** [tempo-riz/deepgram_speech_to_text#4]
Hello! 

Thank you for creating this Dart SDK for Deepgram, we get asked a lot about Dart and up until this point we didn't have a good project to send people to.

I wanted to ask how you'd feel about us mentioning this project in our [documentation as a Community sponsored SDK?](https://developers.deepgram.com/docs/introduction)  Along side our official SDKs.

By doing this it might draw attention to this project and result in people reporting issues are wanting to help maintain it.

Just let us know if this is something you'd be interested in and we can make Deepgram users more aware of it.

**Comment by tempo-riz** [comment]
Hey ! 
It would be my pleasure :) 
Let me know if you need anything

**Comment by jpvajda** [comment]
@tempo-riz  Would you be interested in joining our Deepgram Discord Server? We can try to connect you with others looking to help maintain this project.

https://dpgr.am/discord

If you do join just send me a message and we can connect more.
