### ISSUE TITLE
Text to Speech Feature

### ISSUE THREAD

**Issue by levlau** [tempo-riz/deepgram_speech_to_text#6]
Hi,
you did absolutely great work! This is exactly what i was looking for.
The speech to text is working perfectly, so i wanted to ask you if you also planned to create a text to speech functionality?
This would make it complete and would come in really handy when creating AI voice chats, which is probably often requested from now on.
Cheers

**Comment by tempo-riz** [comment]
Hey @levlau glad you like it :)
I plan to support TTS as Deepgram's new endpoints allow.
I was waiting to see if there was demand for it, so since there is I will update the pacakge soon with it !

**Comment by tempo-riz** [comment]
I just added support for TTS in 2.1.0 :) 
check `deepgram.speakFromText` !
